# Copyright (c) 2026 ADBC Drivers Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Reference: https://iceberg.apache.org/docs/latest/spark-configuration/
javax.security.auth.useSubjectCredsOnly      false

spark.master                                 local[*]
spark.network.timeout                        300s
spark.kryoserializer.buffer.max              1g
spark.kerberos.renewal.credentials           ccache
spark.kerberos.keytab                        /var/keytabs/hive.keytab
spark.kerberos.principal                     hiveuser/hive-metastore@KDC.LOCAL
hadoop.security.authentication               kerberos
hadoop.security.authorization                false

# S3 (MinIO)
spark.hadoop.fs.s3a.access.key                 admin
spark.hadoop.fs.s3a.secret.key                 password
spark.hadoop.fs.s3a.endpoint                   http://minio:9000
spark.hadoop.fs.s3a.path.style.access          true
spark.hadoop.fs.s3a.impl                       org.apache.hadoop.fs.s3a.S3AFileSystem
spark.hadoop.fs.s3a.connection.ssl.enabled     false

# Hive metastore
spark.sql.hive.metastore.version               4.0.1
spark.sql.hive.metastore.jars                  path
spark.sql.hive.metastore.jars.path             /opt/hive4-metastore-jars/*
spark.hive.metastore.uris                      thrift://hive4-metastore:9083
spark.hive.metastore.sasl.enabled              false
spark.hive.server2.authentication              NONE
spark.hive.server2.useSSL                      false
spark.hive.server2.hive.server2.transport.mode binary
spark.hive.server2.thrift.bind.host            0.0.0.0
spark.hive.server2.thrift.port                 10000
spark.sql.warehouse.dir                        /opt/spark-data/warehouse
