[libdefaults]
  default_realm = KDC.LOCAL
  dns_lookup_kdc = false
  dns_lookup_realm = false

[realms]
  KDC.LOCAL = {
    kdc_ports = 88,750
    kadmind_port = 749
    kdc = kerberos
    admin_server = kerberos
    kdc_timeout = 10sec
  }

[logging]
  default = FILE:/var/log/kerberos/krb5libs.log
  kdc = FILE:/var/log/kerberos/krb5kdc.log
  admin_server = FILE:/var/log/kerberos/kadmind.log
