# Livy Configuration
# Reference: https://livy.apache.org/docs/latest/configuration.html

livy.server.host = 0.0.0.0
livy.server.port = 8998

livy.spark.master = local[*]
livy.spark.deploy-mode = client

livy.server.request-header-size = 131072
livy.server.response-header-size = 131072

livy.server.session.timeout = 1h
livy.server.session.timeout-check = true

# Enable HiveContext for Iceberg catalog access
livy.repl.enable-hive-context = true

