# Reference: https://iceberg.apache.org/docs/latest/spark-configuration/

spark.master                                 local[*]
spark.network.timeout                        300s
spark.kryoserializer.buffer.max              1g

# Iceberg
# spark.jars                                   /opt/spark/jars/iceberg-spark-runtime-3.5_2.12-1.7.0.jar
# spark.sql.extensions                         org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions
# spark.sql.catalog.iceberg                    org.apache.iceberg.spark.SparkCatalog
# spark.sql.catalog.iceberg.type               hive
# spark.sql.catalog.iceberg.uri                thrift://hive-metastore:9083
# spark.sql.catalog.iceberg.warehouse          /opt/spark-data/warehouse
# spark.sql.defaultCatalog                     iceberg

# Hive metastore
spark.hive.metastore.uris                      thrift://hive-metastore:9083
spark.hive.server2.authentication              NOSASL
spark.hive.server2.useSSL                      false
spark.hive.server2.hive.server2.transport.mode binary
spark.sql.warehouse.dir                        /opt/spark-data/warehouse

