# Reference: https://iceberg.apache.org/docs/latest/spark-configuration/
javax.security.auth.useSubjectCredsOnly      false

spark.master                                 local[*]
spark.network.timeout                        300s
spark.kryoserializer.buffer.max              1g
spark.kerberos.renewal.credentials           ccache
spark.kerberos.keytab                        /var/keytabs/hive.keytab
spark.kerberos.principal                     hiveuser/hive-metastore@KDC.LOCAL
hadoop.security.authentication               kerberos
hadoop.security.authorization                false

# Iceberg
# spark.jars                                   /opt/spark/jars/iceberg-spark-runtime-3.5_2.12-1.7.0.jar
# spark.sql.extensions                         org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions
# spark.sql.catalog.iceberg                    org.apache.iceberg.spark.SparkCatalog
# spark.sql.catalog.iceberg.type               hive
# spark.sql.catalog.iceberg.uri                thrift://hive-metastore:9083
# spark.sql.catalog.iceberg.warehouse          /opt/spark-data/warehouse
# spark.sql.defaultCatalog                     iceberg

# Hive metastore
spark.hive.metastore.uris                      thrift://hive-metastore:9083
spark.hive.metastore.sasl.enabled              false
spark.hive.server2.authentication              NONE
spark.hive.server2.useSSL                      false
spark.hive.server2.hive.server2.transport.mode binary
spark.hive.server2.thrift.bind.host            0.0.0.0
spark.hive.server2.thrift.port                 10000
spark.sql.warehouse.dir                        /opt/spark-data/warehouse

